name: wanna_chat_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  logging: ^1.2.0

  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  objectbox: ^4.0.2

  http: ^1.2.2
  beautiful_soup_dart: ^0.3.0
  puppeteer: ^3.15.0

  langchain: ^0.7.7
  langchain_community: ^0.3.2
  langchain_openai: ^0.7.2
  #langchain_supabase: ^0.1.1+3

  shared_model:
    path: ../shared_model

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  lint: ^2.3.0
