name: wanna_chat_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  logging: ^1.2.0

  shelf_cors_headers: ^0.1.5
  dart_frog: ^1.1.0

  langchain: ^0.6.0+1
  langchain_community: ^0.1.0+2
  langchain_openai: ^0.5.1+1

  shared_model:
    path: ../shared_model

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  lint: ^2.3.0
