name: shared_model
description: Just some shared data models
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"


dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  lint: ^2.3.0
  test: ^1.25.8
